### ISSUE TITLE
Create visualisations having the same temporal span

### ISSUE THREAD

**Issue by thanosbnt** [FutureCitiesCatapult/SharingCitiesDashboard#35]
It would be good if the users can view data with different temporal frequency in a common temporal extent. This would require resampling of one versus the other

eg. variable x temporal frequency is in minutes
variable y temporal frequency is in days

**Comment by sassalley** [comment]
@thanosbnt does this get addressed through front filling in the DB? Or at the moment does the API just pass the data with it's existing timestamps to the front end?

**Comment by thanosbnt** [comment]
closed as being addressed by PR#106
